### ISSUE TITLE
where is the mlpconv layer

### ISSUE THREAD

**Issue by samo313** [fengyunxiaozi/LDCNN#1]
Hi 
would you please show me part of the code which is belonging to MLPCONV layer.

thanks in advance

**Comment by fengyunxiaozi** [comment]
The mlpconv layer is defined in the script ldcnn_initialize.m (line 21-47).
`net.layers{end+1} = struct('type', 'conv', ...
                           'name','conv6',...
                           'weights', {{f*randn(3,3,512,4096, 'single'), zeros(1,4096,'single')}}, ...
                           'learningRate', lr, ...
                           'stride', [1 1], ...
                           'pad', [0 0 0 0]) ;

net.layers{end+1} = struct('type', 'relu','name','relu6');

net.layers{end+1} = struct('type', 'conv', ...
                           'name','cccp1',...
                           'weights', {{f*randn(1,1,4096,4096, 'single'), zeros(1,4096,'single')}}, ...
                           'learningRate', lr, ...
                           'stride', [1 1], ...
                           'pad', [0 0 0 0]) ;
                       
net.layers{end+1} = struct('type', 'relu','name','relu_cccp1');


net.layers{end+1} = struct('type', 'conv', ...
                           'name','cccp2',...
                           'weights', {{f*randn(1,1,4096,30, 'single'), zeros(1,30,'single')}}, ...
                           'learningRate', 0.001*lr, ...
                           'stride', [1 1], ...
                           'pad', [0 0 0 0]) ;
                       
net.layers{end+1} = struct('type', 'relu','name','relu_cccp2');`
hope this can help you!

**Comment by iiwindii** [comment]
The mlpconv layer is defined in the script ldcnn_initialize.m (line 21-47) as listed below.
```
net.layers{end+1} = struct('type', 'conv', ...
                           'name','conv6',...
                           'weights', {{f*randn(3,3,512,4096, 'single'), zeros(1,4096,'single')}}, ...
                           'learningRate', lr, ...
                           'stride', [1 1], ...
                           'pad', [0 0 0 0]) ;

net.layers{end+1} = struct('type', 'relu','name','relu6');

net.layers{end+1} = struct('type', 'conv', ...
                           'name','cccp1',...
                           'weights', {{f*randn(1,1,4096,4096, 'single'), zeros(1,4096,'single')}}, ...
                           'learningRate', lr, ...
                           'stride', [1 1], ...
                           'pad', [0 0 0 0]) ;
                       
net.layers{end+1} = struct('type', 'relu','name','relu_cccp1');


net.layers{end+1} = struct('type', 'conv', ...
                           'name','cccp2',...
                           'weights', {{f*randn(1,1,4096,30, 'single'), zeros(1,30,'single')}}, ...
                           'learningRate', 0.001*lr, ...
                           'stride', [1 1], ...
                           'pad', [0 0 0 0]) ;
                       
net.layers{end+1} = struct('type', 'relu','name','relu_cccp2');
```
You could refer to the paper "Network In Network" where the mlpconv layer is from. Hope this can help you.

**Comment by samo313** [comment]
thanks a million :).
